// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKQ5RwWHuPhmFa2YqIjoBTsxizkV79xns',
    appId: '1:608293451507:web:11a354a1b00f8986ab6986',
    messagingSenderId: '608293451507',
    projectId: 'vidstream-87509',
    authDomain: 'vidstream-87509.firebaseapp.com',
    storageBucket: 'vidstream-87509.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0k-FUkJdZDRoG_YVHz2XegJXvy--R0jE',
    appId: '1:608293451507:android:56ec363fab10e216ab6986',
    messagingSenderId: '608293451507',
    projectId: 'vidstream-87509',
    storageBucket: 'vidstream-87509.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC1LZTztbg2zD7EPpHh-XFi4TkmoD47Vg',
    appId: '1:608293451507:ios:1382edf7e0fe0d10ab6986',
    messagingSenderId: '608293451507',
    projectId: 'vidstream-87509',
    storageBucket: 'vidstream-87509.appspot.com',
    iosBundleId: 'com.example.vidstream',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC1LZTztbg2zD7EPpHh-XFi4TkmoD47Vg',
    appId: '1:608293451507:ios:1382edf7e0fe0d10ab6986',
    messagingSenderId: '608293451507',
    projectId: 'vidstream-87509',
    storageBucket: 'vidstream-87509.appspot.com',
    iosBundleId: 'com.example.vidstream',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKQ5RwWHuPhmFa2YqIjoBTsxizkV79xns',
    appId: '1:608293451507:web:20f39413359c3e30ab6986',
    messagingSenderId: '608293451507',
    projectId: 'vidstream-87509',
    authDomain: 'vidstream-87509.firebaseapp.com',
    storageBucket: 'vidstream-87509.appspot.com',
  );
}
